version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: danishraza212083
      POSTGRES_DB: fastapi
    volumes:
      - fastapi_postgres_data_temp:/var/lib/postgresql/data

  app:
    build: .
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file: .env

volumes:
  fastapi_postgres_data_temp:
