apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: danishraza212083/fastapi-app:latest
          ports:
            - containerPort: 9000
          envFrom:
            - secretRef:
                name: fastapi-secret
