apiVersion: v1
kind: Service
metadata:
  name: postgres  # This name is used as the hostname by your FastAPI app
spec:
  selector:
    app: postgres  # Must match the 'app' label in your postgres Deployment
  ports:
    - port: 5432        # Port exposed inside the cluster
      targetPort: 5432  # Port the PostgreSQL container listens on
