apiVersion: v1
kind: Secret
metadata:
  name: fastapi-secret
type: Opaque
stringData:
  database_hostname: "postgres"
  database_port: "5432"
  database_username: "postgres"
  database_password: "danishraza212083"
  database_name: "fastapi"
  secret_key: "09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7"
  algorithm: "HS256"
  access_token_expire_minutes: "30"
