apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  type: LoadBalancer
  selector:
    app: fastapi
  ports:
    - protocol: TCP
      port: 9000        # Kubernetes service port
      targetPort: 9000  # Port inside the container
      nodePort: 30007   # External port (can be 30000-32767)
