name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.13.3
      uses: actions/setup-python@v4
      with:
        python-version: '3.13.3'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint code with flake8
      run: |
        pip install flake8
        flake8 app --max-line-length=400

    - name: Build Docker image
      run: docker build -t fastapi-app .

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Tag Docker image
      run: docker tag fastapi-app danishraza212083/fastapi-app:latest

    - name: Push Docker image
      run: docker push danishraza212083/fastapi-app:latest
